# Generated by Django 3.0.5 on 2020-11-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0009_auto_20201119_2355'),
        ('IT6041App', '0008_merge_20201112_2342'),
    ]

    operations = [
    ]
