# Generated by Django 3.0.5 on 2020-11-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT6041App', '0010_merge_20201120_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
